lgu_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: LguAdminBundle:Default:index }

lgu_admin:
    resource: "@LguAdminBundle/Controller/AdminController.php"
    type:     annotation