_login_secured:
    resource: "@AcmeDemoBundle/Controller/LoginController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

contact:
    path: /contact
    defaults: { _controller: AcmeDemoBundle:Hello:contact }